//These definitions use a lovely feature of the Cortex-M4: For each bit of the
//GPIO registers, there is a corresponding word, where the low bit is mapped
//to that same bit, and the other bits are unused. That allows direct access
//to each individual bit without any bit manipulation.
#ifndef _MICRON_PIN_REGS_NEW_H_
#define _MICRON_PIN_REGS_NEW_H_

//Port Data Output Register
#define CORE_PIN0_PDOR  GPIO_BITBAND_PTR(CORE_PIN0_PORTREG,  CORE_PIN0_BIT)
#define CORE_PIN1_PDOR  GPIO_BITBAND_PTR(CORE_PIN1_PORTREG,  CORE_PIN1_BIT)
#define CORE_PIN2_PDOR  GPIO_BITBAND_PTR(CORE_PIN2_PORTREG,  CORE_PIN2_BIT)
#define CORE_PIN3_PDOR  GPIO_BITBAND_PTR(CORE_PIN3_PORTREG,  CORE_PIN3_BIT)
#define CORE_PIN4_PDOR  GPIO_BITBAND_PTR(CORE_PIN4_PORTREG,  CORE_PIN4_BIT)
#define CORE_PIN5_PDOR  GPIO_BITBAND_PTR(CORE_PIN5_PORTREG,  CORE_PIN5_BIT)
#define CORE_PIN6_PDOR  GPIO_BITBAND_PTR(CORE_PIN6_PORTREG,  CORE_PIN6_BIT)
#define CORE_PIN7_PDOR  GPIO_BITBAND_PTR(CORE_PIN7_PORTREG,  CORE_PIN7_BIT)
#define CORE_PIN8_PDOR  GPIO_BITBAND_PTR(CORE_PIN8_PORTREG,  CORE_PIN8_BIT)
#define CORE_PIN9_PDOR  GPIO_BITBAND_PTR(CORE_PIN9_PORTREG,  CORE_PIN9_BIT)
#define CORE_PIN10_PDOR GPIO_BITBAND_PTR(CORE_PIN10_PORTREG, CORE_PIN10_BIT)
#define CORE_PIN11_PDOR GPIO_BITBAND_PTR(CORE_PIN11_PORTREG, CORE_PIN11_BIT)
#define CORE_PIN12_PDOR GPIO_BITBAND_PTR(CORE_PIN12_PORTREG, CORE_PIN12_BIT)
#define CORE_PIN13_PDOR GPIO_BITBAND_PTR(CORE_PIN13_PORTREG, CORE_PIN13_BIT)
#define CORE_PIN14_PDOR GPIO_BITBAND_PTR(CORE_PIN14_PORTREG, CORE_PIN14_BIT)
#define CORE_PIN15_PDOR GPIO_BITBAND_PTR(CORE_PIN15_PORTREG, CORE_PIN15_BIT)
#define CORE_PIN16_PDOR GPIO_BITBAND_PTR(CORE_PIN16_PORTREG, CORE_PIN16_BIT)
#define CORE_PIN17_PDOR GPIO_BITBAND_PTR(CORE_PIN17_PORTREG, CORE_PIN17_BIT)
#define CORE_PIN18_PDOR GPIO_BITBAND_PTR(CORE_PIN18_PORTREG, CORE_PIN18_BIT)
#define CORE_PIN19_PDOR GPIO_BITBAND_PTR(CORE_PIN19_PORTREG, CORE_PIN19_BIT)
#define CORE_PIN20_PDOR GPIO_BITBAND_PTR(CORE_PIN20_PORTREG, CORE_PIN20_BIT)
#define CORE_PIN21_PDOR GPIO_BITBAND_PTR(CORE_PIN21_PORTREG, CORE_PIN21_BIT)
#define CORE_PIN22_PDOR GPIO_BITBAND_PTR(CORE_PIN22_PORTREG, CORE_PIN22_BIT)
#define CORE_PIN23_PDOR GPIO_BITBAND_PTR(CORE_PIN23_PORTREG, CORE_PIN23_BIT)
#define CORE_PIN24_PDOR GPIO_BITBAND_PTR(CORE_PIN24_PORTREG, CORE_PIN24_BIT)
#define CORE_PIN25_PDOR GPIO_BITBAND_PTR(CORE_PIN25_PORTREG, CORE_PIN25_BIT)
#define CORE_PIN26_PDOR GPIO_BITBAND_PTR(CORE_PIN26_PORTREG, CORE_PIN26_BIT)
#define CORE_PIN27_PDOR GPIO_BITBAND_PTR(CORE_PIN27_PORTREG, CORE_PIN27_BIT)
#define CORE_PIN28_PDOR GPIO_BITBAND_PTR(CORE_PIN28_PORTREG, CORE_PIN28_BIT)
#define CORE_PIN29_PDOR GPIO_BITBAND_PTR(CORE_PIN29_PORTREG, CORE_PIN29_BIT)
#define CORE_PIN30_PDOR GPIO_BITBAND_PTR(CORE_PIN30_PORTREG, CORE_PIN30_BIT)
#define CORE_PIN31_PDOR GPIO_BITBAND_PTR(CORE_PIN31_PORTREG, CORE_PIN31_BIT)
#define CORE_PIN32_PDOR GPIO_BITBAND_PTR(CORE_PIN32_PORTREG, CORE_PIN32_BIT)
#define CORE_PIN33_PDOR GPIO_BITBAND_PTR(CORE_PIN33_PORTREG, CORE_PIN33_BIT)

//Port Set Output Register
#define CORE_PIN0_PSOR  GPIO_BITBAND_PTR(CORE_PIN0_PORTSET,  CORE_PIN0_BIT)
#define CORE_PIN1_PSOR  GPIO_BITBAND_PTR(CORE_PIN1_PORTSET,  CORE_PIN1_BIT)
#define CORE_PIN2_PSOR  GPIO_BITBAND_PTR(CORE_PIN2_PORTSET,  CORE_PIN2_BIT)
#define CORE_PIN3_PSOR  GPIO_BITBAND_PTR(CORE_PIN3_PORTSET,  CORE_PIN3_BIT)
#define CORE_PIN4_PSOR  GPIO_BITBAND_PTR(CORE_PIN4_PORTSET,  CORE_PIN4_BIT)
#define CORE_PIN5_PSOR  GPIO_BITBAND_PTR(CORE_PIN5_PORTSET,  CORE_PIN5_BIT)
#define CORE_PIN6_PSOR  GPIO_BITBAND_PTR(CORE_PIN6_PORTSET,  CORE_PIN6_BIT)
#define CORE_PIN7_PSOR  GPIO_BITBAND_PTR(CORE_PIN7_PORTSET,  CORE_PIN7_BIT)
#define CORE_PIN8_PSOR  GPIO_BITBAND_PTR(CORE_PIN8_PORTSET,  CORE_PIN8_BIT)
#define CORE_PIN9_PSOR  GPIO_BITBAND_PTR(CORE_PIN9_PORTSET,  CORE_PIN9_BIT)
#define CORE_PIN10_PSOR GPIO_BITBAND_PTR(CORE_PIN10_PORTSET, CORE_PIN10_BIT)
#define CORE_PIN11_PSOR GPIO_BITBAND_PTR(CORE_PIN11_PORTSET, CORE_PIN11_BIT)
#define CORE_PIN12_PSOR GPIO_BITBAND_PTR(CORE_PIN12_PORTSET, CORE_PIN12_BIT)
#define CORE_PIN13_PSOR GPIO_BITBAND_PTR(CORE_PIN13_PORTSET, CORE_PIN13_BIT)
#define CORE_PIN14_PSOR GPIO_BITBAND_PTR(CORE_PIN14_PORTSET, CORE_PIN14_BIT)
#define CORE_PIN15_PSOR GPIO_BITBAND_PTR(CORE_PIN15_PORTSET, CORE_PIN15_BIT)
#define CORE_PIN16_PSOR GPIO_BITBAND_PTR(CORE_PIN16_PORTSET, CORE_PIN16_BIT)
#define CORE_PIN17_PSOR GPIO_BITBAND_PTR(CORE_PIN17_PORTSET, CORE_PIN17_BIT)
#define CORE_PIN18_PSOR GPIO_BITBAND_PTR(CORE_PIN18_PORTSET, CORE_PIN18_BIT)
#define CORE_PIN19_PSOR GPIO_BITBAND_PTR(CORE_PIN19_PORTSET, CORE_PIN19_BIT)
#define CORE_PIN20_PSOR GPIO_BITBAND_PTR(CORE_PIN20_PORTSET, CORE_PIN20_BIT)
#define CORE_PIN21_PSOR GPIO_BITBAND_PTR(CORE_PIN21_PORTSET, CORE_PIN21_BIT)
#define CORE_PIN22_PSOR GPIO_BITBAND_PTR(CORE_PIN22_PORTSET, CORE_PIN22_BIT)
#define CORE_PIN23_PSOR GPIO_BITBAND_PTR(CORE_PIN23_PORTSET, CORE_PIN23_BIT)
#define CORE_PIN24_PSOR GPIO_BITBAND_PTR(CORE_PIN24_PORTSET, CORE_PIN24_BIT)
#define CORE_PIN25_PSOR GPIO_BITBAND_PTR(CORE_PIN25_PORTSET, CORE_PIN25_BIT)
#define CORE_PIN26_PSOR GPIO_BITBAND_PTR(CORE_PIN26_PORTSET, CORE_PIN26_BIT)
#define CORE_PIN27_PSOR GPIO_BITBAND_PTR(CORE_PIN27_PORTSET, CORE_PIN27_BIT)
#define CORE_PIN28_PSOR GPIO_BITBAND_PTR(CORE_PIN28_PORTSET, CORE_PIN28_BIT)
#define CORE_PIN29_PSOR GPIO_BITBAND_PTR(CORE_PIN29_PORTSET, CORE_PIN29_BIT)
#define CORE_PIN30_PSOR GPIO_BITBAND_PTR(CORE_PIN30_PORTSET, CORE_PIN30_BIT)
#define CORE_PIN31_PSOR GPIO_BITBAND_PTR(CORE_PIN31_PORTSET, CORE_PIN31_BIT)
#define CORE_PIN32_PSOR GPIO_BITBAND_PTR(CORE_PIN32_PORTSET, CORE_PIN32_BIT)
#define CORE_PIN33_PSOR GPIO_BITBAND_PTR(CORE_PIN33_PORTSET, CORE_PIN33_BIT)

//Port Clear Output Register
#define CORE_PIN0_PCOR  GPIO_BITBAND_PTR(CORE_PIN0_PORTCLEAR,  CORE_PIN0_BIT)
#define CORE_PIN1_PCOR  GPIO_BITBAND_PTR(CORE_PIN1_PORTCLEAR,  CORE_PIN1_BIT)
#define CORE_PIN2_PCOR  GPIO_BITBAND_PTR(CORE_PIN2_PORTCLEAR,  CORE_PIN2_BIT)
#define CORE_PIN3_PCOR  GPIO_BITBAND_PTR(CORE_PIN3_PORTCLEAR,  CORE_PIN3_BIT)
#define CORE_PIN4_PCOR  GPIO_BITBAND_PTR(CORE_PIN4_PORTCLEAR,  CORE_PIN4_BIT)
#define CORE_PIN5_PCOR  GPIO_BITBAND_PTR(CORE_PIN5_PORTCLEAR,  CORE_PIN5_BIT)
#define CORE_PIN6_PCOR  GPIO_BITBAND_PTR(CORE_PIN6_PORTCLEAR,  CORE_PIN6_BIT)
#define CORE_PIN7_PCOR  GPIO_BITBAND_PTR(CORE_PIN7_PORTCLEAR,  CORE_PIN7_BIT)
#define CORE_PIN8_PCOR  GPIO_BITBAND_PTR(CORE_PIN8_PORTCLEAR,  CORE_PIN8_BIT)
#define CORE_PIN9_PCOR  GPIO_BITBAND_PTR(CORE_PIN9_PORTCLEAR,  CORE_PIN9_BIT)
#define CORE_PIN10_PCOR GPIO_BITBAND_PTR(CORE_PIN10_PORTCLEAR, CORE_PIN10_BIT)
#define CORE_PIN11_PCOR GPIO_BITBAND_PTR(CORE_PIN11_PORTCLEAR, CORE_PIN11_BIT)
#define CORE_PIN12_PCOR GPIO_BITBAND_PTR(CORE_PIN12_PORTCLEAR, CORE_PIN12_BIT)
#define CORE_PIN13_PCOR GPIO_BITBAND_PTR(CORE_PIN13_PORTCLEAR, CORE_PIN13_BIT)
#define CORE_PIN14_PCOR GPIO_BITBAND_PTR(CORE_PIN14_PORTCLEAR, CORE_PIN14_BIT)
#define CORE_PIN15_PCOR GPIO_BITBAND_PTR(CORE_PIN15_PORTCLEAR, CORE_PIN15_BIT)
#define CORE_PIN16_PCOR GPIO_BITBAND_PTR(CORE_PIN16_PORTCLEAR, CORE_PIN16_BIT)
#define CORE_PIN17_PCOR GPIO_BITBAND_PTR(CORE_PIN17_PORTCLEAR, CORE_PIN17_BIT)
#define CORE_PIN18_PCOR GPIO_BITBAND_PTR(CORE_PIN18_PORTCLEAR, CORE_PIN18_BIT)
#define CORE_PIN19_PCOR GPIO_BITBAND_PTR(CORE_PIN19_PORTCLEAR, CORE_PIN19_BIT)
#define CORE_PIN20_PCOR GPIO_BITBAND_PTR(CORE_PIN20_PORTCLEAR, CORE_PIN20_BIT)
#define CORE_PIN21_PCOR GPIO_BITBAND_PTR(CORE_PIN21_PORTCLEAR, CORE_PIN21_BIT)
#define CORE_PIN22_PCOR GPIO_BITBAND_PTR(CORE_PIN22_PORTCLEAR, CORE_PIN22_BIT)
#define CORE_PIN23_PCOR GPIO_BITBAND_PTR(CORE_PIN23_PORTCLEAR, CORE_PIN23_BIT)
#define CORE_PIN24_PCOR GPIO_BITBAND_PTR(CORE_PIN24_PORTCLEAR, CORE_PIN24_BIT)
#define CORE_PIN25_PCOR GPIO_BITBAND_PTR(CORE_PIN25_PORTCLEAR, CORE_PIN25_BIT)
#define CORE_PIN26_PCOR GPIO_BITBAND_PTR(CORE_PIN26_PORTCLEAR, CORE_PIN26_BIT)
#define CORE_PIN27_PCOR GPIO_BITBAND_PTR(CORE_PIN27_PORTCLEAR, CORE_PIN27_BIT)
#define CORE_PIN28_PCOR GPIO_BITBAND_PTR(CORE_PIN28_PORTCLEAR, CORE_PIN28_BIT)
#define CORE_PIN29_PCOR GPIO_BITBAND_PTR(CORE_PIN29_PORTCLEAR, CORE_PIN29_BIT)
#define CORE_PIN30_PCOR GPIO_BITBAND_PTR(CORE_PIN30_PORTCLEAR, CORE_PIN30_BIT)
#define CORE_PIN31_PCOR GPIO_BITBAND_PTR(CORE_PIN31_PORTCLEAR, CORE_PIN31_BIT)
#define CORE_PIN32_PCOR GPIO_BITBAND_PTR(CORE_PIN32_PORTCLEAR, CORE_PIN32_BIT)
#define CORE_PIN33_PCOR GPIO_BITBAND_PTR(CORE_PIN33_PORTCLEAR, CORE_PIN33_BIT)

//Port Toggle Output Register
#define CORE_PIN0_PTOR  GPIO_BITBAND_PTR(CORE_PIN0_PORTTOGGLE,  CORE_PIN0_BIT)
#define CORE_PIN1_PTOR  GPIO_BITBAND_PTR(CORE_PIN1_PORTTOGGLE,  CORE_PIN1_BIT)
#define CORE_PIN2_PTOR  GPIO_BITBAND_PTR(CORE_PIN2_PORTTOGGLE,  CORE_PIN2_BIT)
#define CORE_PIN3_PTOR  GPIO_BITBAND_PTR(CORE_PIN3_PORTTOGGLE,  CORE_PIN3_BIT)
#define CORE_PIN4_PTOR  GPIO_BITBAND_PTR(CORE_PIN4_PORTTOGGLE,  CORE_PIN4_BIT)
#define CORE_PIN5_PTOR  GPIO_BITBAND_PTR(CORE_PIN5_PORTTOGGLE,  CORE_PIN5_BIT)
#define CORE_PIN6_PTOR  GPIO_BITBAND_PTR(CORE_PIN6_PORTTOGGLE,  CORE_PIN6_BIT)
#define CORE_PIN7_PTOR  GPIO_BITBAND_PTR(CORE_PIN7_PORTTOGGLE,  CORE_PIN7_BIT)
#define CORE_PIN8_PTOR  GPIO_BITBAND_PTR(CORE_PIN8_PORTTOGGLE,  CORE_PIN8_BIT)
#define CORE_PIN9_PTOR  GPIO_BITBAND_PTR(CORE_PIN9_PORTTOGGLE,  CORE_PIN9_BIT)
#define CORE_PIN10_PTOR GPIO_BITBAND_PTR(CORE_PIN10_PORTTOGGLE, CORE_PIN10_BIT)
#define CORE_PIN11_PTOR GPIO_BITBAND_PTR(CORE_PIN11_PORTTOGGLE, CORE_PIN11_BIT)
#define CORE_PIN12_PTOR GPIO_BITBAND_PTR(CORE_PIN12_PORTTOGGLE, CORE_PIN12_BIT)
#define CORE_PIN13_PTOR GPIO_BITBAND_PTR(CORE_PIN13_PORTTOGGLE, CORE_PIN13_BIT)
#define CORE_PIN14_PTOR GPIO_BITBAND_PTR(CORE_PIN14_PORTTOGGLE, CORE_PIN14_BIT)
#define CORE_PIN15_PTOR GPIO_BITBAND_PTR(CORE_PIN15_PORTTOGGLE, CORE_PIN15_BIT)
#define CORE_PIN16_PTOR GPIO_BITBAND_PTR(CORE_PIN16_PORTTOGGLE, CORE_PIN16_BIT)
#define CORE_PIN17_PTOR GPIO_BITBAND_PTR(CORE_PIN17_PORTTOGGLE, CORE_PIN17_BIT)
#define CORE_PIN18_PTOR GPIO_BITBAND_PTR(CORE_PIN18_PORTTOGGLE, CORE_PIN18_BIT)
#define CORE_PIN19_PTOR GPIO_BITBAND_PTR(CORE_PIN19_PORTTOGGLE, CORE_PIN19_BIT)
#define CORE_PIN20_PTOR GPIO_BITBAND_PTR(CORE_PIN20_PORTTOGGLE, CORE_PIN20_BIT)
#define CORE_PIN21_PTOR GPIO_BITBAND_PTR(CORE_PIN21_PORTTOGGLE, CORE_PIN21_BIT)
#define CORE_PIN22_PTOR GPIO_BITBAND_PTR(CORE_PIN22_PORTTOGGLE, CORE_PIN22_BIT)
#define CORE_PIN23_PTOR GPIO_BITBAND_PTR(CORE_PIN23_PORTTOGGLE, CORE_PIN23_BIT)
#define CORE_PIN24_PTOR GPIO_BITBAND_PTR(CORE_PIN24_PORTTOGGLE, CORE_PIN24_BIT)
#define CORE_PIN25_PTOR GPIO_BITBAND_PTR(CORE_PIN25_PORTTOGGLE, CORE_PIN25_BIT)
#define CORE_PIN26_PTOR GPIO_BITBAND_PTR(CORE_PIN26_PORTTOGGLE, CORE_PIN26_BIT)
#define CORE_PIN27_PTOR GPIO_BITBAND_PTR(CORE_PIN27_PORTTOGGLE, CORE_PIN27_BIT)
#define CORE_PIN28_PTOR GPIO_BITBAND_PTR(CORE_PIN28_PORTTOGGLE, CORE_PIN28_BIT)
#define CORE_PIN29_PTOR GPIO_BITBAND_PTR(CORE_PIN29_PORTTOGGLE, CORE_PIN29_BIT)
#define CORE_PIN30_PTOR GPIO_BITBAND_PTR(CORE_PIN30_PORTTOGGLE, CORE_PIN30_BIT)
#define CORE_PIN31_PTOR GPIO_BITBAND_PTR(CORE_PIN31_PORTTOGGLE, CORE_PIN31_BIT)
#define CORE_PIN32_PTOR GPIO_BITBAND_PTR(CORE_PIN32_PORTTOGGLE, CORE_PIN32_BIT)
#define CORE_PIN33_PTOR GPIO_BITBAND_PTR(CORE_PIN33_PORTTOGGLE, CORE_PIN33_BIT)

//Port Data Direction Register
#define CORE_PIN0_PDDR  GPIO_BITBAND_PTR(CORE_PIN0_DDRREG,  CORE_PIN0_BIT)
#define CORE_PIN1_PDDR  GPIO_BITBAND_PTR(CORE_PIN1_DDRREG,  CORE_PIN1_BIT)
#define CORE_PIN2_PDDR  GPIO_BITBAND_PTR(CORE_PIN2_DDRREG,  CORE_PIN2_BIT)
#define CORE_PIN3_PDDR  GPIO_BITBAND_PTR(CORE_PIN3_DDRREG,  CORE_PIN3_BIT)
#define CORE_PIN4_PDDR  GPIO_BITBAND_PTR(CORE_PIN4_DDRREG,  CORE_PIN4_BIT)
#define CORE_PIN5_PDDR  GPIO_BITBAND_PTR(CORE_PIN5_DDRREG,  CORE_PIN5_BIT)
#define CORE_PIN6_PDDR  GPIO_BITBAND_PTR(CORE_PIN6_DDRREG,  CORE_PIN6_BIT)
#define CORE_PIN7_PDDR  GPIO_BITBAND_PTR(CORE_PIN7_DDRREG,  CORE_PIN7_BIT)
#define CORE_PIN8_PDDR  GPIO_BITBAND_PTR(CORE_PIN8_DDRREG,  CORE_PIN8_BIT)
#define CORE_PIN9_PDDR  GPIO_BITBAND_PTR(CORE_PIN9_DDRREG,  CORE_PIN9_BIT)
#define CORE_PIN10_PDDR GPIO_BITBAND_PTR(CORE_PIN10_DDRREG, CORE_PIN10_BIT)
#define CORE_PIN11_PDDR GPIO_BITBAND_PTR(CORE_PIN11_DDRREG, CORE_PIN11_BIT)
#define CORE_PIN12_PDDR GPIO_BITBAND_PTR(CORE_PIN12_DDRREG, CORE_PIN12_BIT)
#define CORE_PIN13_PDDR GPIO_BITBAND_PTR(CORE_PIN13_DDRREG, CORE_PIN13_BIT)
#define CORE_PIN14_PDDR GPIO_BITBAND_PTR(CORE_PIN14_DDRREG, CORE_PIN14_BIT)
#define CORE_PIN15_PDDR GPIO_BITBAND_PTR(CORE_PIN15_DDRREG, CORE_PIN15_BIT)
#define CORE_PIN16_PDDR GPIO_BITBAND_PTR(CORE_PIN16_DDRREG, CORE_PIN16_BIT)
#define CORE_PIN17_PDDR GPIO_BITBAND_PTR(CORE_PIN17_DDRREG, CORE_PIN17_BIT)
#define CORE_PIN18_PDDR GPIO_BITBAND_PTR(CORE_PIN18_DDRREG, CORE_PIN18_BIT)
#define CORE_PIN19_PDDR GPIO_BITBAND_PTR(CORE_PIN19_DDRREG, CORE_PIN19_BIT)
#define CORE_PIN20_PDDR GPIO_BITBAND_PTR(CORE_PIN20_DDRREG, CORE_PIN20_BIT)
#define CORE_PIN21_PDDR GPIO_BITBAND_PTR(CORE_PIN21_DDRREG, CORE_PIN21_BIT)
#define CORE_PIN22_PDDR GPIO_BITBAND_PTR(CORE_PIN22_DDRREG, CORE_PIN22_BIT)
#define CORE_PIN23_PDDR GPIO_BITBAND_PTR(CORE_PIN23_DDRREG, CORE_PIN23_BIT)
#define CORE_PIN24_PDDR GPIO_BITBAND_PTR(CORE_PIN24_DDRREG, CORE_PIN24_BIT)
#define CORE_PIN25_PDDR GPIO_BITBAND_PTR(CORE_PIN25_DDRREG, CORE_PIN25_BIT)
#define CORE_PIN26_PDDR GPIO_BITBAND_PTR(CORE_PIN26_DDRREG, CORE_PIN26_BIT)
#define CORE_PIN27_PDDR GPIO_BITBAND_PTR(CORE_PIN27_DDRREG, CORE_PIN27_BIT)
#define CORE_PIN28_PDDR GPIO_BITBAND_PTR(CORE_PIN28_DDRREG, CORE_PIN28_BIT)
#define CORE_PIN29_PDDR GPIO_BITBAND_PTR(CORE_PIN29_DDRREG, CORE_PIN29_BIT)
#define CORE_PIN30_PDDR GPIO_BITBAND_PTR(CORE_PIN30_DDRREG, CORE_PIN30_BIT)
#define CORE_PIN31_PDDR GPIO_BITBAND_PTR(CORE_PIN31_DDRREG, CORE_PIN31_BIT)
#define CORE_PIN32_PDDR GPIO_BITBAND_PTR(CORE_PIN32_DDRREG, CORE_PIN32_BIT)
#define CORE_PIN33_PDDR GPIO_BITBAND_PTR(CORE_PIN33_DDRREG, CORE_PIN33_BIT)

//Port Data Input Register
#define CORE_PIN0_PDIR  GPIO_BITBAND_PTR(CORE_PIN0_PINREG,  CORE_PIN0_BIT)
#define CORE_PIN1_PDIR  GPIO_BITBAND_PTR(CORE_PIN1_PINREG,  CORE_PIN1_BIT)
#define CORE_PIN2_PDIR  GPIO_BITBAND_PTR(CORE_PIN2_PINREG,  CORE_PIN2_BIT)
#define CORE_PIN3_PDIR  GPIO_BITBAND_PTR(CORE_PIN3_PINREG,  CORE_PIN3_BIT)
#define CORE_PIN4_PDIR  GPIO_BITBAND_PTR(CORE_PIN4_PINREG,  CORE_PIN4_BIT)
#define CORE_PIN5_PDIR  GPIO_BITBAND_PTR(CORE_PIN5_PINREG,  CORE_PIN5_BIT)
#define CORE_PIN6_PDIR  GPIO_BITBAND_PTR(CORE_PIN6_PINREG,  CORE_PIN6_BIT)
#define CORE_PIN7_PDIR  GPIO_BITBAND_PTR(CORE_PIN7_PINREG,  CORE_PIN7_BIT)
#define CORE_PIN8_PDIR  GPIO_BITBAND_PTR(CORE_PIN8_PINREG,  CORE_PIN8_BIT)
#define CORE_PIN9_PDIR  GPIO_BITBAND_PTR(CORE_PIN9_PINREG,  CORE_PIN9_BIT)
#define CORE_PIN10_PDIR GPIO_BITBAND_PTR(CORE_PIN10_PINREG, CORE_PIN10_BIT)
#define CORE_PIN11_PDIR GPIO_BITBAND_PTR(CORE_PIN11_PINREG, CORE_PIN11_BIT)
#define CORE_PIN12_PDIR GPIO_BITBAND_PTR(CORE_PIN12_PINREG, CORE_PIN12_BIT)
#define CORE_PIN13_PDIR GPIO_BITBAND_PTR(CORE_PIN13_PINREG, CORE_PIN13_BIT)
#define CORE_PIN14_PDIR GPIO_BITBAND_PTR(CORE_PIN14_PINREG, CORE_PIN14_BIT)
#define CORE_PIN15_PDIR GPIO_BITBAND_PTR(CORE_PIN15_PINREG, CORE_PIN15_BIT)
#define CORE_PIN16_PDIR GPIO_BITBAND_PTR(CORE_PIN16_PINREG, CORE_PIN16_BIT)
#define CORE_PIN17_PDIR GPIO_BITBAND_PTR(CORE_PIN17_PINREG, CORE_PIN17_BIT)
#define CORE_PIN18_PDIR GPIO_BITBAND_PTR(CORE_PIN18_PINREG, CORE_PIN18_BIT)
#define CORE_PIN19_PDIR GPIO_BITBAND_PTR(CORE_PIN19_PINREG, CORE_PIN19_BIT)
#define CORE_PIN20_PDIR GPIO_BITBAND_PTR(CORE_PIN20_PINREG, CORE_PIN20_BIT)
#define CORE_PIN21_PDIR GPIO_BITBAND_PTR(CORE_PIN21_PINREG, CORE_PIN21_BIT)
#define CORE_PIN22_PDIR GPIO_BITBAND_PTR(CORE_PIN22_PINREG, CORE_PIN22_BIT)
#define CORE_PIN23_PDIR GPIO_BITBAND_PTR(CORE_PIN23_PINREG, CORE_PIN23_BIT)
#define CORE_PIN24_PDIR GPIO_BITBAND_PTR(CORE_PIN24_PINREG, CORE_PIN24_BIT)
#define CORE_PIN25_PDIR GPIO_BITBAND_PTR(CORE_PIN25_PINREG, CORE_PIN25_BIT)
#define CORE_PIN26_PDIR GPIO_BITBAND_PTR(CORE_PIN26_PINREG, CORE_PIN26_BIT)
#define CORE_PIN27_PDIR GPIO_BITBAND_PTR(CORE_PIN27_PINREG, CORE_PIN27_BIT)
#define CORE_PIN28_PDIR GPIO_BITBAND_PTR(CORE_PIN28_PINREG, CORE_PIN28_BIT)
#define CORE_PIN29_PDIR GPIO_BITBAND_PTR(CORE_PIN29_PINREG, CORE_PIN29_BIT)
#define CORE_PIN30_PDIR GPIO_BITBAND_PTR(CORE_PIN30_PINREG, CORE_PIN30_BIT)
#define CORE_PIN31_PDIR GPIO_BITBAND_PTR(CORE_PIN31_PINREG, CORE_PIN31_BIT)
#define CORE_PIN32_PDIR GPIO_BITBAND_PTR(CORE_PIN32_PINREG, CORE_PIN32_BIT)
#define CORE_PIN33_PDIR GPIO_BITBAND_PTR(CORE_PIN33_PINREG, CORE_PIN33_BIT)

//Port Control Register
//For completeness' sake. These are multi-bit registers, so there's
//little sense mapping them. (I guess I could map each individual bit of
//them, but that seems not terribly useful, as it's not often you want to
//change only one. Feel free to do that if you want though.)
#define CORE_PIN0_PCR  CORE_PIN0_CONFIG
#define CORE_PIN1_PCR  CORE_PIN1_CONFIG
#define CORE_PIN2_PCR  CORE_PIN2_CONFIG
#define CORE_PIN3_PCR  CORE_PIN3_CONFIG
#define CORE_PIN4_PCR  CORE_PIN4_CONFIG
#define CORE_PIN5_PCR  CORE_PIN5_CONFIG
#define CORE_PIN6_PCR  CORE_PIN6_CONFIG
#define CORE_PIN7_PCR  CORE_PIN7_CONFIG
#define CORE_PIN8_PCR  CORE_PIN8_CONFIG
#define CORE_PIN9_PCR  CORE_PIN9_CONFIG
#define CORE_PIN10_PCR CORE_PIN10_CONFIG
#define CORE_PIN11_PCR CORE_PIN11_CONFIG
#define CORE_PIN12_PCR CORE_PIN12_CONFIG
#define CORE_PIN13_PCR CORE_PIN13_CONFIG
#define CORE_PIN14_PCR CORE_PIN14_CONFIG
#define CORE_PIN15_PCR CORE_PIN15_CONFIG
#define CORE_PIN16_PCR CORE_PIN16_CONFIG
#define CORE_PIN17_PCR CORE_PIN17_CONFIG
#define CORE_PIN18_PCR CORE_PIN18_CONFIG
#define CORE_PIN19_PCR CORE_PIN19_CONFIG
#define CORE_PIN20_PCR CORE_PIN20_CONFIG
#define CORE_PIN21_PCR CORE_PIN21_CONFIG
#define CORE_PIN22_PCR CORE_PIN22_CONFIG
#define CORE_PIN23_PCR CORE_PIN23_CONFIG
#define CORE_PIN24_PCR CORE_PIN24_CONFIG
#define CORE_PIN25_PCR CORE_PIN25_CONFIG
#define CORE_PIN26_PCR CORE_PIN26_CONFIG
#define CORE_PIN27_PCR CORE_PIN27_CONFIG
#define CORE_PIN28_PCR CORE_PIN28_CONFIG
#define CORE_PIN29_PCR CORE_PIN29_CONFIG
#define CORE_PIN30_PCR CORE_PIN30_CONFIG
#define CORE_PIN31_PCR CORE_PIN31_CONFIG
#define CORE_PIN32_PCR CORE_PIN32_CONFIG
#define CORE_PIN33_PCR CORE_PIN33_CONFIG

#endif //_MICRON_PIN_REGS_NEW_H_
