# Name of your project. Used to name the output files.
PROJECT=ssd1306

# What CPU clock to use, in MHz. (default: 72)
#CPU_MHZ=72

# Whether to show what's being done during the build process. (default: yes)
#LOG_INFO=0

# Whether to output each command as it's executed during the build process.
# (default: no)
#LOG_COMMANDS=1

# Whether to build a .map file for debugging. (default: no)
# Warning: Changing this to 0 won't delete existing map files.
# Make sure you aren't working with an outdated map.
#BUILD_MAP=1

# Whether to include standard libraries. These can occupy quite a bit of space.
# (default: no)
#WITH_STDLIBS=0

# Include the makefile for the board we're targeting.
include micron/make/teensy31.mk
