//Teensy 4.1

//Memory
#define FLASH_SIZE 8126464 //bytes
#define RAM_START 0x1C000000
#define RAM_SIZE 1048576 //bytes
#define EEPROM_SIZE 4284 //bytes

//UART
#define NUM_UART 8
#define UART_REG_OFFSET(port) (0x1000 * (port))
#define UART_REG_BASE(port)   (0x4006A000 + UART_REG_OFFSET(port))
//hardware pin assignments for each UART
#define UART0_TX_PIN  1
#define UART0_RX_PIN  0
#define UART1_TX_PIN 10
#define UART1_RX_PIN  9
#define UART2_TX_PIN  8
#define UART2_RX_PIN  7

//I2C/IIC
#define NUM_I2C 3
#define I2C_REG_OFFSET(port) (0x1000 * (port))
#define I2C_REG_BASE(port)   (0x40066000 + I2C_REG_OFFSET(port))
//hardware pin assignments for each I2C
#define I2C0_SCL_PIN 19
#define I2C0_SDA_PIN 18
#define I2C1_SCL_PIN 16 //not 17; I2C1 pins are reverse order of I2C0
#define I2C1_SDA_PIN 17

//SPI
#define NUM_SPI 3

//CRC
#define NUM_HW_CRC 1

//RTC
//RTC prescalar counts up to this per second
#define RTC_PRESCALAR_FREQ 32768
//multiply/divide by this to convert between prescalar and microseconds
#define RTC_PRESCALAR_RATIO ROUND_TO_INT(1000000.0 / RTC_PRESCALAR_FREQ)

//NVIC/IRQ
#define NVIC_BASE ((volatile uint32_t*)0xE000E100)

#define KINETISK_UART0
#define KINETISK_UART0_FIFO
#define KINETISK_UART1
#define KINETISK_UART1_FIFO
#define KINETISK_UART2

//GPIO
//Number of pins of each type available.
#define CORE_NUM_TOTAL_PINS     55
#define CORE_NUM_DIGITAL        55 //# digital GPIO
#define CORE_NUM_INTERRUPT      55 //# GPIO with interrupts
#define CORE_NUM_ANALOG         18 //# analog GPIO
#define CORE_NUM_PWM            31 //# PWM GPIO

//Converts an address and bit index of a register in the GPIO region to the
//corresponding single-bit (bitband) register address.
#define GPIO_BITBAND_ADDR(reg, bit) \
	(((((uint32_t)&(reg) & 0x3FFFFFFF) * 32) + (4 * (bit))) | 0x42000000)
#define GPIO_BITBAND_PTR(reg, bit) \
	(*(volatile uint32_t*)GPIO_BITBAND_ADDR((reg), (bit)))

//The bit number of each pin within its GPIO registers.
//The pins' internal ordering is quite different from their physical layout.
#define CORE_PIN0_BIT		16
#define CORE_PIN1_BIT		17
#define CORE_PIN2_BIT		0
#define CORE_PIN3_BIT		12
#define CORE_PIN4_BIT		13
#define CORE_PIN5_BIT		7
#define CORE_PIN6_BIT		4
#define CORE_PIN7_BIT		2
#define CORE_PIN8_BIT		3
#define CORE_PIN9_BIT		3
#define CORE_PIN10_BIT		4
#define CORE_PIN11_BIT		6
#define CORE_PIN12_BIT		7
#define CORE_PIN13_BIT		5
#define CORE_PIN14_BIT		1
#define CORE_PIN15_BIT		0
#define CORE_PIN16_BIT		0
#define CORE_PIN17_BIT		1
#define CORE_PIN18_BIT		3
#define CORE_PIN19_BIT		2
#define CORE_PIN20_BIT		5
#define CORE_PIN21_BIT		6
#define CORE_PIN22_BIT		1
#define CORE_PIN23_BIT		2
#define CORE_PIN24_BIT		5
#define CORE_PIN25_BIT		19
#define CORE_PIN26_BIT		1
#define CORE_PIN27_BIT		9
#define CORE_PIN28_BIT		8
#define CORE_PIN29_BIT		10
#define CORE_PIN30_BIT		11
#define CORE_PIN31_BIT		0
#define CORE_PIN32_BIT		18
#define CORE_PIN33_BIT		4

#define CORE_ADC0_PIN		14
#define CORE_ADC1_PIN		15
#define CORE_ADC2_PIN		16
#define CORE_ADC3_PIN		17
#define CORE_ADC4_PIN		18
#define CORE_ADC5_PIN		19
#define CORE_ADC6_PIN		20
#define CORE_ADC7_PIN		21
#define CORE_ADC8_PIN		22
#define CORE_ADC9_PIN		23
#define CORE_ADC10_PIN		34
#define CORE_ADC11_PIN		35
#define CORE_ADC12_PIN		36
#define CORE_ADC13_PIN		37

#define CORE_RXD0_PIN		0
#define CORE_TXD0_PIN		1
#define CORE_RXD1_PIN		9
#define CORE_TXD1_PIN		10
#define CORE_RXD2_PIN		7
#define CORE_TXD2_PIN		8

#define CORE_INT0_PIN		0
#define CORE_INT1_PIN		1
#define CORE_INT2_PIN		2
#define CORE_INT3_PIN		3
#define CORE_INT4_PIN		4
#define CORE_INT5_PIN		5
#define CORE_INT6_PIN		6
#define CORE_INT7_PIN		7
#define CORE_INT8_PIN		8
#define CORE_INT9_PIN		9
#define CORE_INT10_PIN		10
#define CORE_INT11_PIN		11
#define CORE_INT12_PIN		12
#define CORE_INT13_PIN		13
#define CORE_INT14_PIN		14
#define CORE_INT15_PIN		15
#define CORE_INT16_PIN		16
#define CORE_INT17_PIN		17
#define CORE_INT18_PIN		18
#define CORE_INT19_PIN		19
#define CORE_INT20_PIN		20
#define CORE_INT21_PIN		21
#define CORE_INT22_PIN		22
#define CORE_INT23_PIN		23
#define CORE_INT24_PIN		24
#define CORE_INT25_PIN		25
#define CORE_INT26_PIN		26
#define CORE_INT27_PIN		27
#define CORE_INT28_PIN		28
#define CORE_INT29_PIN		29
#define CORE_INT30_PIN		30
#define CORE_INT31_PIN		31
#define CORE_INT32_PIN		32
#define CORE_INT33_PIN		33
#define CORE_INT_EVERY_PIN	1

//the multi-bit Port Data Output Register for each pin.
#define CORE_PIN0_PORTREG  GPIOB_PDOR
#define CORE_PIN1_PORTREG  GPIOB_PDOR
#define CORE_PIN2_PORTREG  GPIOD_PDOR
#define CORE_PIN3_PORTREG  GPIOA_PDOR
#define CORE_PIN4_PORTREG  GPIOA_PDOR
#define CORE_PIN5_PORTREG  GPIOD_PDOR
#define CORE_PIN6_PORTREG  GPIOD_PDOR
#define CORE_PIN7_PORTREG  GPIOD_PDOR
#define CORE_PIN8_PORTREG  GPIOD_PDOR
#define CORE_PIN9_PORTREG  GPIOC_PDOR
#define CORE_PIN10_PORTREG GPIOC_PDOR
#define CORE_PIN11_PORTREG GPIOC_PDOR
#define CORE_PIN12_PORTREG GPIOC_PDOR
#define CORE_PIN13_PORTREG GPIOC_PDOR
#define CORE_PIN14_PORTREG GPIOD_PDOR
#define CORE_PIN15_PORTREG GPIOC_PDOR
#define CORE_PIN16_PORTREG GPIOB_PDOR
#define CORE_PIN17_PORTREG GPIOB_PDOR
#define CORE_PIN18_PORTREG GPIOB_PDOR
#define CORE_PIN19_PORTREG GPIOB_PDOR
#define CORE_PIN20_PORTREG GPIOD_PDOR
#define CORE_PIN21_PORTREG GPIOD_PDOR
#define CORE_PIN22_PORTREG GPIOC_PDOR
#define CORE_PIN23_PORTREG GPIOC_PDOR
#define CORE_PIN24_PORTREG GPIOA_PDOR
#define CORE_PIN25_PORTREG GPIOB_PDOR
#define CORE_PIN26_PORTREG GPIOE_PDOR
#define CORE_PIN27_PORTREG GPIOC_PDOR
#define CORE_PIN28_PORTREG GPIOC_PDOR
#define CORE_PIN29_PORTREG GPIOC_PDOR
#define CORE_PIN30_PORTREG GPIOC_PDOR
#define CORE_PIN31_PORTREG GPIOE_PDOR
#define CORE_PIN32_PORTREG GPIOB_PDOR
#define CORE_PIN33_PORTREG GPIOA_PDOR

//the multi-bit Port Set Output Register for each pin.
#define CORE_PIN0_PORTSET  GPIOB_PSOR
#define CORE_PIN1_PORTSET  GPIOB_PSOR
#define CORE_PIN2_PORTSET  GPIOD_PSOR
#define CORE_PIN3_PORTSET  GPIOA_PSOR
#define CORE_PIN4_PORTSET  GPIOA_PSOR
#define CORE_PIN5_PORTSET  GPIOD_PSOR
#define CORE_PIN6_PORTSET  GPIOD_PSOR
#define CORE_PIN7_PORTSET  GPIOD_PSOR
#define CORE_PIN8_PORTSET  GPIOD_PSOR
#define CORE_PIN9_PORTSET  GPIOC_PSOR
#define CORE_PIN10_PORTSET GPIOC_PSOR
#define CORE_PIN11_PORTSET GPIOC_PSOR
#define CORE_PIN12_PORTSET GPIOC_PSOR
#define CORE_PIN13_PORTSET GPIOC_PSOR
#define CORE_PIN14_PORTSET GPIOD_PSOR
#define CORE_PIN15_PORTSET GPIOC_PSOR
#define CORE_PIN16_PORTSET GPIOB_PSOR
#define CORE_PIN17_PORTSET GPIOB_PSOR
#define CORE_PIN18_PORTSET GPIOB_PSOR
#define CORE_PIN19_PORTSET GPIOB_PSOR
#define CORE_PIN20_PORTSET GPIOD_PSOR
#define CORE_PIN21_PORTSET GPIOD_PSOR
#define CORE_PIN22_PORTSET GPIOC_PSOR
#define CORE_PIN23_PORTSET GPIOC_PSOR
#define CORE_PIN24_PORTSET GPIOA_PSOR
#define CORE_PIN25_PORTSET GPIOB_PSOR
#define CORE_PIN26_PORTSET GPIOE_PSOR
#define CORE_PIN27_PORTSET GPIOC_PSOR
#define CORE_PIN28_PORTSET GPIOC_PSOR
#define CORE_PIN29_PORTSET GPIOC_PSOR
#define CORE_PIN30_PORTSET GPIOC_PSOR
#define CORE_PIN31_PORTSET GPIOE_PSOR
#define CORE_PIN32_PORTSET GPIOB_PSOR
#define CORE_PIN33_PORTSET GPIOA_PSOR

//the multi-bit Port Clear Output Register for each pin.
#define CORE_PIN0_PORTCLEAR  GPIOB_PCOR
#define CORE_PIN1_PORTCLEAR  GPIOB_PCOR
#define CORE_PIN2_PORTCLEAR  GPIOD_PCOR
#define CORE_PIN3_PORTCLEAR  GPIOA_PCOR
#define CORE_PIN4_PORTCLEAR  GPIOA_PCOR
#define CORE_PIN5_PORTCLEAR  GPIOD_PCOR
#define CORE_PIN6_PORTCLEAR  GPIOD_PCOR
#define CORE_PIN7_PORTCLEAR  GPIOD_PCOR
#define CORE_PIN8_PORTCLEAR  GPIOD_PCOR
#define CORE_PIN9_PORTCLEAR  GPIOC_PCOR
#define CORE_PIN10_PORTCLEAR GPIOC_PCOR
#define CORE_PIN11_PORTCLEAR GPIOC_PCOR
#define CORE_PIN12_PORTCLEAR GPIOC_PCOR
#define CORE_PIN13_PORTCLEAR GPIOC_PCOR
#define CORE_PIN14_PORTCLEAR GPIOD_PCOR
#define CORE_PIN15_PORTCLEAR GPIOC_PCOR
#define CORE_PIN16_PORTCLEAR GPIOB_PCOR
#define CORE_PIN17_PORTCLEAR GPIOB_PCOR
#define CORE_PIN18_PORTCLEAR GPIOB_PCOR
#define CORE_PIN19_PORTCLEAR GPIOB_PCOR
#define CORE_PIN20_PORTCLEAR GPIOD_PCOR
#define CORE_PIN21_PORTCLEAR GPIOD_PCOR
#define CORE_PIN22_PORTCLEAR GPIOC_PCOR
#define CORE_PIN23_PORTCLEAR GPIOC_PCOR
#define CORE_PIN24_PORTCLEAR GPIOA_PCOR
#define CORE_PIN25_PORTCLEAR GPIOB_PCOR
#define CORE_PIN26_PORTCLEAR GPIOE_PCOR
#define CORE_PIN27_PORTCLEAR GPIOC_PCOR
#define CORE_PIN28_PORTCLEAR GPIOC_PCOR
#define CORE_PIN29_PORTCLEAR GPIOC_PCOR
#define CORE_PIN30_PORTCLEAR GPIOC_PCOR
#define CORE_PIN31_PORTCLEAR GPIOE_PCOR
#define CORE_PIN32_PORTCLEAR GPIOB_PCOR
#define CORE_PIN33_PORTCLEAR GPIOA_PCOR

//the multi-bit Port Toggle Output Register for each pin.
//(not defined in original Teensy code)
#define CORE_PIN0_PORTTOGGLE  GPIOB_PTOR
#define CORE_PIN1_PORTTOGGLE  GPIOB_PTOR
#define CORE_PIN2_PORTTOGGLE  GPIOD_PTOR
#define CORE_PIN3_PORTTOGGLE  GPIOA_PTOR
#define CORE_PIN4_PORTTOGGLE  GPIOA_PTOR
#define CORE_PIN5_PORTTOGGLE  GPIOD_PTOR
#define CORE_PIN6_PORTTOGGLE  GPIOD_PTOR
#define CORE_PIN7_PORTTOGGLE  GPIOD_PTOR
#define CORE_PIN8_PORTTOGGLE  GPIOD_PTOR
#define CORE_PIN9_PORTTOGGLE  GPIOC_PTOR
#define CORE_PIN10_PORTTOGGLE GPIOC_PTOR
#define CORE_PIN11_PORTTOGGLE GPIOC_PTOR
#define CORE_PIN12_PORTTOGGLE GPIOC_PTOR
#define CORE_PIN13_PORTTOGGLE GPIOC_PTOR
#define CORE_PIN14_PORTTOGGLE GPIOD_PTOR
#define CORE_PIN15_PORTTOGGLE GPIOC_PTOR
#define CORE_PIN16_PORTTOGGLE GPIOB_PTOR
#define CORE_PIN17_PORTTOGGLE GPIOB_PTOR
#define CORE_PIN18_PORTTOGGLE GPIOB_PTOR
#define CORE_PIN19_PORTTOGGLE GPIOB_PTOR
#define CORE_PIN20_PORTTOGGLE GPIOD_PTOR
#define CORE_PIN21_PORTTOGGLE GPIOD_PTOR
#define CORE_PIN22_PORTTOGGLE GPIOC_PTOR
#define CORE_PIN23_PORTTOGGLE GPIOC_PTOR
#define CORE_PIN24_PORTTOGGLE GPIOA_PTOR
#define CORE_PIN25_PORTTOGGLE GPIOB_PTOR
#define CORE_PIN26_PORTTOGGLE GPIOE_PTOR
#define CORE_PIN27_PORTTOGGLE GPIOC_PTOR
#define CORE_PIN28_PORTTOGGLE GPIOC_PTOR
#define CORE_PIN29_PORTTOGGLE GPIOC_PTOR
#define CORE_PIN30_PORTTOGGLE GPIOC_PTOR
#define CORE_PIN31_PORTTOGGLE GPIOE_PTOR
#define CORE_PIN32_PORTTOGGLE GPIOB_PTOR
#define CORE_PIN33_PORTTOGGLE GPIOA_PTOR

//the multi-bit Port Data Direction Register for each pin.
#define CORE_PIN0_DDRREG  GPIOB_PDDR
#define CORE_PIN1_DDRREG  GPIOB_PDDR
#define CORE_PIN2_DDRREG  GPIOD_PDDR
#define CORE_PIN3_DDRREG  GPIOA_PDDR
#define CORE_PIN4_DDRREG  GPIOA_PDDR
#define CORE_PIN5_DDRREG  GPIOD_PDDR
#define CORE_PIN6_DDRREG  GPIOD_PDDR
#define CORE_PIN7_DDRREG  GPIOD_PDDR
#define CORE_PIN8_DDRREG  GPIOD_PDDR
#define CORE_PIN9_DDRREG  GPIOC_PDDR
#define CORE_PIN10_DDRREG GPIOC_PDDR
#define CORE_PIN11_DDRREG GPIOC_PDDR
#define CORE_PIN12_DDRREG GPIOC_PDDR
#define CORE_PIN13_DDRREG GPIOC_PDDR
#define CORE_PIN14_DDRREG GPIOD_PDDR
#define CORE_PIN15_DDRREG GPIOC_PDDR
#define CORE_PIN16_DDRREG GPIOB_PDDR
#define CORE_PIN17_DDRREG GPIOB_PDDR
#define CORE_PIN18_DDRREG GPIOB_PDDR
#define CORE_PIN19_DDRREG GPIOB_PDDR
#define CORE_PIN20_DDRREG GPIOD_PDDR
#define CORE_PIN21_DDRREG GPIOD_PDDR
#define CORE_PIN22_DDRREG GPIOC_PDDR
#define CORE_PIN23_DDRREG GPIOC_PDDR
#define CORE_PIN24_DDRREG GPIOA_PDDR
#define CORE_PIN25_DDRREG GPIOB_PDDR
#define CORE_PIN26_DDRREG GPIOE_PDDR
#define CORE_PIN27_DDRREG GPIOC_PDDR
#define CORE_PIN28_DDRREG GPIOC_PDDR
#define CORE_PIN29_DDRREG GPIOC_PDDR
#define CORE_PIN30_DDRREG GPIOC_PDDR
#define CORE_PIN31_DDRREG GPIOE_PDDR
#define CORE_PIN32_DDRREG GPIOB_PDDR
#define CORE_PIN33_DDRREG GPIOA_PDDR

//the multi-bit Port Data Input Register for each pin.
#define CORE_PIN0_PINREG  GPIOB_PDIR
#define CORE_PIN1_PINREG  GPIOB_PDIR
#define CORE_PIN2_PINREG  GPIOD_PDIR
#define CORE_PIN3_PINREG  GPIOA_PDIR
#define CORE_PIN4_PINREG  GPIOA_PDIR
#define CORE_PIN5_PINREG  GPIOD_PDIR
#define CORE_PIN6_PINREG  GPIOD_PDIR
#define CORE_PIN7_PINREG  GPIOD_PDIR
#define CORE_PIN8_PINREG  GPIOD_PDIR
#define CORE_PIN9_PINREG  GPIOC_PDIR
#define CORE_PIN10_PINREG GPIOC_PDIR
#define CORE_PIN11_PINREG GPIOC_PDIR
#define CORE_PIN12_PINREG GPIOC_PDIR
#define CORE_PIN13_PINREG GPIOC_PDIR
#define CORE_PIN14_PINREG GPIOD_PDIR
#define CORE_PIN15_PINREG GPIOC_PDIR
#define CORE_PIN16_PINREG GPIOB_PDIR
#define CORE_PIN17_PINREG GPIOB_PDIR
#define CORE_PIN18_PINREG GPIOB_PDIR
#define CORE_PIN19_PINREG GPIOB_PDIR
#define CORE_PIN20_PINREG GPIOD_PDIR
#define CORE_PIN21_PINREG GPIOD_PDIR
#define CORE_PIN22_PINREG GPIOC_PDIR
#define CORE_PIN23_PINREG GPIOC_PDIR
#define CORE_PIN24_PINREG GPIOA_PDIR
#define CORE_PIN25_PINREG GPIOB_PDIR
#define CORE_PIN26_PINREG GPIOE_PDIR
#define CORE_PIN27_PINREG GPIOC_PDIR
#define CORE_PIN28_PINREG GPIOC_PDIR
#define CORE_PIN29_PINREG GPIOC_PDIR
#define CORE_PIN30_PINREG GPIOC_PDIR
#define CORE_PIN31_PINREG GPIOE_PDIR
#define CORE_PIN32_PINREG GPIOB_PDIR
#define CORE_PIN33_PINREG GPIOA_PDIR

//the Port Config Register for each pin.
#define CORE_PIN0_CONFIG  PORTB_PCR16
#define CORE_PIN1_CONFIG  PORTB_PCR17
#define CORE_PIN2_CONFIG  PORTD_PCR0
#define CORE_PIN3_CONFIG  PORTA_PCR12
#define CORE_PIN4_CONFIG  PORTA_PCR13
#define CORE_PIN5_CONFIG  PORTD_PCR7
#define CORE_PIN6_CONFIG  PORTD_PCR4
#define CORE_PIN7_CONFIG  PORTD_PCR2
#define CORE_PIN8_CONFIG  PORTD_PCR3
#define CORE_PIN9_CONFIG  PORTC_PCR3
#define CORE_PIN10_CONFIG PORTC_PCR4
#define CORE_PIN11_CONFIG PORTC_PCR6
#define CORE_PIN12_CONFIG PORTC_PCR7
#define CORE_PIN13_CONFIG PORTC_PCR5
#define CORE_PIN14_CONFIG PORTD_PCR1
#define CORE_PIN15_CONFIG PORTC_PCR0
#define CORE_PIN16_CONFIG PORTB_PCR0
#define CORE_PIN17_CONFIG PORTB_PCR1
#define CORE_PIN18_CONFIG PORTB_PCR3
#define CORE_PIN19_CONFIG PORTB_PCR2
#define CORE_PIN20_CONFIG PORTD_PCR5
#define CORE_PIN21_CONFIG PORTD_PCR6
#define CORE_PIN22_CONFIG PORTC_PCR1
#define CORE_PIN23_CONFIG PORTC_PCR2
#define CORE_PIN24_CONFIG PORTA_PCR5
#define CORE_PIN25_CONFIG PORTB_PCR19
#define CORE_PIN26_CONFIG PORTE_PCR1
#define CORE_PIN27_CONFIG PORTC_PCR9
#define CORE_PIN28_CONFIG PORTC_PCR8
#define CORE_PIN29_CONFIG PORTC_PCR10
#define CORE_PIN30_CONFIG PORTC_PCR11
#define CORE_PIN31_CONFIG PORTE_PCR0
#define CORE_PIN32_CONFIG PORTB_PCR18
#define CORE_PIN33_CONFIG PORTA_PCR4
